[package]
name = "credent"
version = "0.1.0"
description = "Manages ~/.config/<app>/credentials."
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.17.7"
once_cell = "1.4.1"
smol = "0.3.3"
credent_auth_cli = { path = "crate/credent_auth_cli" }
credent_auth_fs = { path = "crate/credent_auth_fs" }
credent_auth_model = { path = "crate/credent_auth_model" }

[workspace]
members = ["crate/*"]
