[package]
name = "credent_auth_cli"
version = "0.1.0"
description = "Reads in credentials from the CLI."
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[dependencies]
rpassword = "5.0.0"
smol = "0.3.3"
credent_auth_model = { path = "../credent_auth_model" }
